networks:
  mlops:
services:
  mlflow:
    image: willemmeints/mlflow:2.1.1
    environment:
      DB_HOST: database
      DB_NAME: mlflow
      DB_USER: postgres
      DB_PASS: ${DB_PASSWORD}
      DB_PORT: 5432
    ports:
      - 5000:5000
    depends_on:
      - database
  workflow_server:
    image: mlops-in-a-can/workflow-server:latest
    build:
      context: docker/images/workflow-server
    environment:
      DB_HOST: database
      DB_NAME: prefect
      DB_USER: postgres
      DB_PASS: ${DB_PASSWORD}
      DB_PORT: 5432
      EXTRA_PIP_PACKAGES: "prefect_aws"
      PREFECT_LOGGING_SERVER_LEVEL: WARNING
    ports:
      - 4200:4200
    depends_on:
      - database
  workflow_agent:
    image: mlops-in-a-can/workflow-agent
    build:
      context: docker/images/workflow-agent
    environment:
      PREFECT_API_URL: http://workflow_server:4200/api
      MLFLOW_TRACKING_URI: http://mlflow:5000
      QUEUE_NAME: default
      EXTRA_PIP_PACKAGES: "prefect_azure adlfs mlflow==2.1.1 python-dotenv==0.21.1 pandas==1.5.3 scikit-learn==1.2.1"
    depends_on:
      - workflow_server
  database:
    image: postgres:14
    networks:
      mlops:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgres/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./docker/volumes/postgres/init:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgres/data/pgdata
  datalake:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
      - 10001:10001
    volumes:
      - azurite_data:/data
    healthcheck:
      test: nc 127.0.0.1 10000 -z
      interval: 1s
      retries: 30
  datalake_init:
    image: mcr.microsoft.com/azure-cli:latest
    depends_on:
      datalake:
        condition: service_healthy
    command:
      - /bin/sh
      - -c 
      - |
        az storage container create --name flows
    environment:
      AZURE_STORAGE_CONNECTION_STRING: ${DATALAKE_CONNECTION_STRING}
volumes:
  postgres_data:
  azurite_data:
