[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "reviews-classification"
version = "0.1.0"
dependencies = [
  
]

[project.optional-dependencies]
dev = ["pytest>=7.2.1", "pytest-cov>=4.0.0"]

[tool.setuptools.packages.find]
namespaces = false
